config/routes.rb
Rails.application.routes.draw do
  resources :entities do
    get 'deposit', to: 'transactions#deposit'
    get 'withdraw', to: 'transactions#withdraw'
    get 'transfer', to: 'transactions#transfer'
    post 'compute', to: 'transactions#compute', on: :collection
  end
  resources :transactions, only: %w[index]
  root 'entities#index'
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_one :wallet, dependent: :destroy

  validates_inclusion_of :type, in: %w[User Team Stock]
  validates :name, :type, presence: true

  after_create :create_wallet

  def create_wallet
    create_wallet!
  end

  delegate :balance, to: :wallet, allow_nil: true
end

# == Schema Information
#
# Table name: entities
#
#  id         :bigint           not null, primary key
#  name       :string
#  type       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  respond_to :html

  def index
    @entities = Entity.all
    respond_with(@entities)
  end

  def show
    respond_with(@entity)
  end

  def new
    @entity = Entity.new(entity_params)
    respond_with(@entity)
  end

  def edit; end

  def create
    @entity = Entity.new(entity_params)
    if @entity.save
      respond_to do |format|
        format.html { redirect_to entities_path, notice: "Quote was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @entity.assign_attributes(entity_params)
    if @entity.save
      respond_to do |format|
        format.html { redirect_to entities_path, notice: "Quote was successfully updated." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @entity.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@entity) }
      format.html         { redirect_to entities_url }
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.fetch(:entity, {}).permit(:name, :type)
  end
end

app/views/entities/_entity.html.erb
  <tr id="<%= dom_id(entity) %>">
    <td><%= entity.name %></td>
    <td><%= entity.type %></td>
    <td><%= entity.balance || 0 %></td>
    <td><%= entity.created_at.to_fs(:short) %></td>
    <td><%= entity.updated_at.to_fs(:short) %></td>
    <td>
      <%= link_to "Show", entity_path(entity.id), class: 'btn btn-light', data: {turbo_frame: :page} %>
      <%= link_to "Edit", edit_entity_path(entity.id), class: 'btn btn-info', data: {turbo_frame: :form_entity} %>
      <%= link_to "Delete", entity_path(entity), class: "btn btn-danger",
        data: { turbo_method: :delete, turbo_confirm: 'are you sure?' } %>
      <%= link_to "Deposit", [entity, :deposit], class: 'btn btn-link', data: {turbo: false} %>
      <%= link_to "Withdraw", [entity, :withdraw], class: 'btn btn-link', data: {turbo: false} %>
      <%= link_to "Transfer", [entity, :transfer], class: 'btn btn-link', data: {turbo: false} %>
    </td>
  </tr>

app/views/entities/_form.html.erb
<%= form_with model: @entity do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name, 'Name' %>
      <%= form.text_field :name, class: 'form-control' %>
  </div>
  <%= form.label :type, 'Type' %>
  <%= form.select :type, options_for_select(%w(User Team Stock), selected: entity.type || 'Stock'),
    {}, {class: 'form-control'} %>
  <div>
    <%= form.submit 'Submit', class: 'btn btn-primary mt-3' %>
    <%= link_to "Cancel", :entities, class: "btn btn-light mt-3" %>
  </div>
<% end %>

app/views/entities/create.turbo_stream.erb
<%= turbo_stream.append(:entities, partial: "entities/entity", locals: { entity: @entity }) %>
<%= turbo_stream.replace :form_entity do %>
  <%= turbo_frame_tag :form_entity %>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= turbo_frame_tag :form_entity do %>
<%= render "entities/form", entity: @entity %>
<% end %>

<br>

<div>
  <%= link_to "Show", entity_path(@entity.id), class: 'btn btn-light' %>
  <%= link_to "Back to entities", entities_path, class: "btn btn-link" %>
</div>

app/views/entities/index.html.erb
<%= turbo_frame_tag :page do %>
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Balance</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="entities">
      <% @entities.each do |entity| %>
        <%= render 'entities/entity', entity: entity %>
      <% end %>
    </tbody>
  </table>
<%= turbo_frame_tag :form_entity do %>
<% end %>

<%= link_to "New entity", new_entity_path, class: "mt-3 btn btn-primary", data: {turbo_frame: :form_entity} %>
<%= link_to "Transactions", transactions_path, class: "btn btn-link mt-3" %>
<% end %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= turbo_frame_tag :form_entity do %>
<%= render "form", entity: @entity %>
<% end %>

<br>

<div>
  <%= link_to "Back to entities", entities_path, class: "btn btn-link" %>
</div>

app/views/entities/show.html.erb
<%= turbo_frame_tag :page do %>

  <dl>
    <dt>Name</dt>
    <dd><%= @entity.name %></dd>
    <dt>Type</dt>
    <dd><%= @entity.type %></dd>
    <dt>Balance</dt>
    <dd><%= @entity.balance || 0 %></dd>
    <dt>Created at</dt>
    <dd><%= @entity.created_at.to_fs(:short) %></dd>
    <dt>Updated at</dt>
    <dd><%= @entity.updated_at.to_fs(:short) %></dd>
  </dl>

<div>
  <%= link_to "Back to entities", root_path, class: "btn btn-link", data: {turbo: false} %>
</div>
<% end %>

app/views/entities/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@entity),partial: "entities/entity", locals: { entity: @entity } %>
<%= turbo_stream.replace :form_entity do %>
  <%= turbo_frame_tag :form_entity %>
<% end %>