config/routes.rb
Rails.application.routes.draw do
  resources :entities do
    get 'deposit', to: 'transactions#deposit'
    get 'withdraw', to: 'transactions#withdraw'
    get 'transfer', to: 'transactions#transfer'
    post 'compute', to: 'transactions#compute', on: :collection
  end
  resources :transactions, only: %w[index]
  root 'entities#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :init_transaction, only: %i[deposit transfer withdraw]
  before_action :set_wallet, only: %i[withdraw transfer]

  respond_to :html

  def index
    @transactions = Transaction.all

    respond_with(@transactions)
  end

  def deposit; end

  def transfer
    @wallets = Wallet.includes(:entity)
                     .where.not(entities: { id: params[:entity_id] })
                     .pluck('entities.name, wallets.id')
  end

  def withdraw; end

  def compute
    raise InvalidTransactionActError unless %w[deposit transfer withdraw].include?(params[:transaction][:act])

    attrs = Transaction.transaction_attrs_strategy(params[:transaction])
    Transaction.send(params[:transaction][:act], *attrs)
    redirect_to entities_path
  end

  private

  def init_transaction
    @transaction = Transaction.new
  end

  def set_wallet
    @wallet = wallet
  end

  def transaction_params
    params.require(:transaction)
          .permit(:amount, :source_wallet_id, :target_wallet_id, :act)
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
  def transaction_row(transaction)
    attrs = [transaction.amount, transaction.source_wallet,
             transaction.target_wallet, transaction.created_at]

    send("transaction_debit_#{transaction.act_type}_type", *attrs)
      .concat(send("transaction_credit_#{transaction.act_type}_type", *attrs))
  end

  def transaction_debit_deposit_type(amount, source, _target, created_at)
    src = source&.entity&.name || '(deleted entity)'
    src += source&.entity&.type ? '(' + source&.entity&.type + ')' : ''
    tag.tr
       .concat(tag.td(amount))
       .concat(tag.td)
       .concat(tag.td("Deposit to #{src}"))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end

  def transaction_credit_deposit_type(amount, _source, _target, created_at)
    tag.tr
       .concat(tag.td)
       .concat(tag.td(amount))
       .concat(tag.td('Cash inflow'))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end

  def transaction_debit_withdraw_type(amount, _source, _target, created_at)
    tag.tr
       .concat(tag.td(amount))
       .concat(tag.td)
       .concat(tag.td('Cash outflow'))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end

  def transaction_credit_withdraw_type(amount, _source, target, created_at)
    trg = target&.entity&.name || '(deleted entity)'
    trg += target&.entity&.type ? "(#{target&.entity&.type})" : ''

    tag.tr
       .concat(tag.td)
       .concat(tag.td(amount))
       .concat(tag.td("Withdraw from #{trg}"))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end

  def transaction_debit_transfer_type(amount, _source, target, created_at)
    trg = target&.entity&.name || '(deleted entity)'
    trg += target&.entity&.type ? "(#{target&.entity&.type})" : ''
    tag.tr
       .concat(tag.td(amount))
       .concat(tag.td)
       .concat(tag.td("Deduct from #{trg}"))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end

  def transaction_credit_transfer_type(amount, source, _target, created_at)
    src = source&.entity&.name || '(deleted entity)'
    src += source&.entity&.type ? '(' + source&.entity&.type + ')' : ''
    tag.tr
       .concat(tag.td)
       .concat(tag.td(amount))
       .concat(tag.td("Transfer to #{src}"))
       .concat(tag.td(created_at.to_fs(:short)))
       .html_safe
  end
end

app/views/transactions/_transaction.html.erb
<%= transaction_row(transaction) %>

app/views/transactions/deposit.html.erb
<h1>Transaction#deposit of <%= fetch_entity_name(params[:entity_id]) %></h1>
<%= form_for @transaction, url: compute_entities_path do |f| %>
  <div class="form-group">
    <%= f.label :amount, 'Amount' %>
    <%= f.number_field :amount, class: 'form-control', required: :required %>
  </div>
  <%= f.hidden_field :act, value: action_name %>
  <%= f.hidden_field :source_wallet_id, value: params[:entity_id] %>
  <%= f.submit 'Process', class: 'btn btn-primary mt-3' %>
<% end %>

<div class="mt-3">
  <%= link_to "Show Entity", entity_path(id: params[:entity_id]), class: 'btn btn-light' %>
  <%= link_to "Back to entities", root_path, class: "btn btn-link" %>
</div>

app/views/transactions/index.html.erb
<%= turbo_frame_tag :page do %>
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Debit</th>
        <th>Credit</th>
        <th>Description</th>
        <th>Created at</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <%= render 'transactions/transaction', transaction: transaction %>
      <% end %>
    </tbody>
  </table>
<%= link_to "Entities", entities_path, class: "btn btn-link" %>
<% end %>

app/views/transactions/transfer.html.erb
<h1>Transfer from <%= fetch_entity_name(params[:entity_id], type: :wallet_id) %></h1>
<%= form_for @transaction, url: compute_entities_path do |f| %>
  <div class="form-group">
    <%= f.label :to, 'Wallet destination' %>
    <%= f.select :target_wallet_id, options_for_select(@wallets), {}, {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :amount, 'Amount' %>
    <%= f.number_field :amount, class: 'form-control', min: 1, max: @wallet.balance, required: :required %>
  </div>
  <%= f.hidden_field :act, value: action_name %>
  <%= f.hidden_field :source_wallet_id, value: params[:entity_id] %>
  <%= f.submit 'Process', class: 'btn btn-primary mt-3' %>
<% end %>

<div class="mt-3">
  <%= link_to "Show Entity", entity_path(id: params[:entity_id]), class: 'btn btn-light', data: {turbo: false} %>
  <%= link_to "Back to entities", root_path, class: "btn btn-link", data: {turbo: false} %>
</div>

app/views/transactions/withdraw.html.erb
<h1>Transaction#withdraw of <%= fetch_entity_name(params[:entity_id]) %></h1>
<%= form_for @transaction, url: compute_entities_path do |f| %>
  <div class="form-group">
    <%= f.label :amount, 'Amount' %>
    <%= f.number_field :amount, class: 'form-control', min: 1, max: @wallet.balance, required: :required %>
  </div>
  <%= f.hidden_field :act, value: action_name %>
  <%= f.hidden_field :target_wallet_id, value: params[:entity_id] %>
  <%= f.submit 'Process', class: 'btn btn-primary mt-3' %>
<% end %>

<div class="mt-3">
  <%= link_to "Show Entity", entity_path(id: params[:entity_id]), class: 'btn btn-light' %>
  <%= link_to "Back to entities", root_path, class: "btn btn-link" %>
</div>